FROM redis:5.0.2-alpine as redis

ENV OSPACKAGES=amd64-packages.txt

WORKDIR /dep
COPY ${OSPACKAGES} /dep

RUN apk --no-cache update && \
    apk --no-cache add $(cat ${OSPACKAGES}) 

WORKDIR /
RUN rm -rf /dep

WORKDIR /module
COPY package.json /module
COPY edge-hooks.js /module
RUN npm install --production

WORKDIR /data

COPY module-entrypoint.sh /usr/local/bin/

EXPOSE 6379
ENTRYPOINT ["module-entrypoint.sh"]
