FROM redis:5.0-rc-alpine as redis
FROM alpine:3.8

COPY --from=redis /usr/local/bin/redis-* /usr/local/bin/

WORKDIR /dep
COPY packages.txt /dep

RUN apk update && \
    apk add $(cat packages.txt) && \
    rm -rf /var/lib/apt/lists/* 

WORKDIR /
RUN rm -rf /dep

WORKDIR /module
COPY package.json /module
COPY edge-hooks.js /module
RUN npm install --production

WORKDIR /data

COPY module-entrypoint.sh /usr/local/bin/

EXPOSE 6379
ENTRYPOINT ["module-entrypoint.sh"]
